export const contentType = {
  text: "text",
  addLiquidity: "addLiquidity",
  removeLiquidity: "removeLiquidity",
  migrateLiquidity: "migrateLiquidity",
  poolSelector: "poolSelector",
  positionSelector: "positionSelector",
  portfolioSelector: "portfolioSelector",
  rangeSelector: "rangeSelector",
  connectWallet: "connectWallet",
  transactionDetails: "transactionDetails",
  chooseMigrationPath: "chooseMigrationPath",
  aiThinking: "aiThinking",
  dos: "dos",
} as const;
